### ISSUE TITLE
Chocolate texture adjustment

### ISSUE THREAD

**Issue by HybridDog** [iisu/minetest-easter-eggs#1]
l played a bit with the chocolate block texture:
Before:
![screenshot_20170415_180057](https://cloud.githubusercontent.com/assets/3192173/25064948/fd51a9a6-2205-11e7-94a1-9d21d1465522.png)
After:
![screenshot_20170415_180036](https://cloud.githubusercontent.com/assets/3192173/25064950/01b43504-2206-11e7-9169-2494e4c6b2a1.png)
![easter_eggs_chocolate_block](https://cloud.githubusercontent.com/assets/3192173/25064970/7f8ed63c-2206-11e7-9059-14b1707d84c9.png)
Both look like chocolate in my opinion.
l'm thinking about spawning big floating chocolate castles with wall, floor and ceiling patterns.

**Comment by iisu** [comment]
This looks great!
Maybe you could alter chocolate egg texture as well and make dark chocolate eggs and dark chocolate blocks. File a pull request with the textures.

About the chocolate castles: this is just a simple mod, doesn't add anything else then the eggs and the blocks you can craft with them. I don't think like spawning big structures fit there.
You can always make your own mod that does so and has my mod as a dependency. I'll be glad to see it.
